service: mattermost-metrics-server

package:
    individually: true

provider:
    name: aws
    runtime: nodejs8.10
    profile: dev-aws
    region: us-east-1
    apiKeys:
        - metricsServerKey

custom:
    webpackIncludeModules: true
    webpack:
        webpackConfig: ./webpack.config.js
        packager: 'npm'

functions:
    index:
        handler: src/ping.default
        timeout: 20
        memorySize: 1024
        events:
            - http:
                  path: /
                  method: get
                  private: true

    ping:
        handler: src/ping.default
        memorySize: 1024
        events:
            - http:
                  path: ping
                  method: get
                  private: true

    get_metrics:
        handler: src/get_metrics.default
        memorySize: 1024
        events:
            - http:
                  path: metrics
                  method: get
                  private: true

    get_metric:
        handler: src/get_metric.default
        memorySize: 1024
        events:
            - http:
                  path: metric/{id}
                  method: get
                  private: true

    post_metric:
        handler: src/post_metric.default
        memorySize: 1024
        events:
            - http:
                  path: metric
                  method: post
                  private: true
            - schedule:
                  rate: rate(5 minutes)
                  enabled: true

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-dotenv-plugin
