{
 "title": "Performance Comparisons",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SELECT DISTINCT server_version FROM traces WHERE $__timeFilter(created_at) AND server_version IS NOT NULL"
   },
   {
    "name": "appVersion",
    "label": "App Version",
    "query": "SELECT DISTINCT app_version FROM traces WHERE $__timeFilter(created_at) AND app_version IS NOT NULL AND server_version IN($server)"
   },
   {
    "name": "buildNumber",
    "label": "Build Number",
    "query": "SELECT DISTINCT build_number FROM traces WHERE $__timeFilter(created_at) AND build_number IS NOT NULL AND server_version IN($server) AND app_version IN($appVersion)"
   },
   {
    "name": "manufacturer",
    "label": "Manufacturer",
    "query": "SELECT DISTINCT manufacturer FROM traces WHERE $__timeFilter(created_at) AND manufacturer IS NOT NULL AND server_version IN($server) AND app_version IN($appVersion) AND build_number IN($buildNumber)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total data collected",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,5y),\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Data collected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  system_name AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Server version",
   "type": "graph",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  server_version AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer) AND\n  build_number != '196'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RN App Version",
   "type": "graph",
   "gridPos": { "h": 18, "w": 20, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  app_version AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Build Number",
   "type": "graph",
   "gridPos": { "h": 17, "w": 20, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  build_number AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Performance Metrics",
   "type": "graph",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "time in seconds" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  trace_name AS metric,\n  avg(trace_dur)/1000000 AS \"trace_dur\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  trace_dur < 20000000 AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer) AND\n  build_number != '196'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}