{
 "title": "Facts",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SELECT DISTINCT server_version FROM traces WHERE $__timeFilter(created_at) AND server_version IS NOT NULL"
   },
   {
    "name": "appVersion",
    "label": "App Version",
    "query": "SELECT DISTINCT app_version FROM traces WHERE $__timeFilter(created_at) AND app_version IS NOT NULL AND server_version IN($server)"
   },
   {
    "name": "buildNumber",
    "label": "Build Number",
    "query": "SELECT DISTINCT build_number FROM traces WHERE $__timeFilter(created_at) AND build_number IS NOT NULL AND server_version IN($server) AND app_version IN($appVersion)"
   },
   {
    "name": "manufacturer",
    "label": "Manufacturer",
    "query": "SELECT DISTINCT manufacturer FROM traces WHERE $__timeFilter(created_at) AND manufacturer IS NOT NULL AND server_version IN($server) AND app_version IN($appVersion) AND build_number IN($buildNumber)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total data collected",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(id)\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)"
    }
   ]
  },
  {
   "title": "Country",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT country)\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)"
    }
   ]
  },
  {
   "title": "Timezone",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT timezone)\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)"
    }
   ]
  },
  {
   "title": "Locale",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT device_locale)\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)"
    }
   ]
  },
  {
   "title": "Unique Device",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT device_unique_id)\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)"
    }
   ]
  },
  {
   "title": "Brand",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT brand)\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)"
    }
   ]
  },
  {
   "title": "Data collected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  system_name AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Country",
   "type": "graph",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  country AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Timezone",
   "type": "graph",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  timezone AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Brand",
   "type": "graph",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  brand AS metric,\n  count(id) AS \"id\"\nFROM traces\nWHERE\n  $__timeFilter(created_at) AND\n  server_version IN($server) AND\n  app_version IN($appVersion) AND\n  build_number IN($buildNumber) AND\n  manufacturer IN($manufacturer)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}